INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pebble", "Smartwatch", 1000, 05012016, 07012016);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ubuntu Edge", "Smartphone", 2000, 01012015, 04012015);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Coolest Cooler", "Computing Hardware", 600, 06012017, 07012017);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Star Citizen", "Video Game", 500, 01012014, 05012014);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Qtum", "Blockchain", 50000, 05012017, 10012017);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tezos", "Blockchain", 40000000, 06012017, 07012017);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("EOS", "Blockchain", 1000000, 02012016, 05012016);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Elio Motors", "Car", 5000, 09012015, 11012015);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mario Kart", "Video Game", 100, 01012018, 02012018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Britt's Flatiron Tuition", "Education", 10000, 02012017, 02012018);

INSERT INTO users (name, age) VALUES ("Britt", 26);
INSERT INTO users (name, age) VALUES ("Jess", 26);
INSERT INTO users (name, age) VALUES ("Justin", 24);
INSERT INTO users (name, age) VALUES ("Sandy", 58);
INSERT INTO users (name, age) VALUES ("Andy", 56);
INSERT INTO users (name, age) VALUES ("Jen", 46);
INSERT INTO users (name, age) VALUES ("Carly", 22);
INSERT INTO users (name, age) VALUES ("Mary", 29);
INSERT INTO users (name, age) VALUES ("Jules", 30);
INSERT INTO users (name, age) VALUES ("Ilana", 35);
INSERT INTO users (name, age) VALUES ("Sarah", 22);
INSERT INTO users (name, age) VALUES ("Caroline", 22);
INSERT INTO users (name, age) VALUES ("Erin", 19);
INSERT INTO users (name, age) VALUES ("Cady", 19);
INSERT INTO users (name, age) VALUES ("Walt", 70);
INSERT INTO users (name, age) VALUES ("Mike", 46);
INSERT INTO users (name, age) VALUES ("John", 68);
INSERT INTO users (name, age) VALUES ("Fabi", 25);
INSERT INTO users (name, age) VALUES ("Judy", 37);
INSERT INTO users (name, age) VALUES ("Lynn", 50);

-- 20 users, 10 projects.  Pick numbers for id's

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 20, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 17, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (550, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (660, 15, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 8);
